# Config for convomniballot.py
# chops the first part of the sequence number used to move RCV to the end
#trim_sequence_prefix: 9

#contest_map_file: contmap.tsv
#candidate_map_file: candmap.tsv

# The district ID for all voters in this election:
election_voting_district: 0

# The result_style code for turnout giving voting_group_ids and result_stat_type_ids
turnout_result_style: EMTE

# Number of digits in the bt subdirectory for ballot type number
bt_digits: 3

# Suffix on election-base to select alternate
#election_base_suffix: "-t"

# Patterns to match retention candidate names in retention contest question text
retention_pats:
    - Justice {candidate_name} be elected

# Patterns to match contests restricted to a partisan ballot
contest_party_pats:
    - PRESIDENT OF THE UNITED STATES
    - MEMBER, COUNTY CENTRAL COMMITTEE

approval_required:
    '2/3':
        - H
        - J
        - O
        - P
        - Q
        - S
    '55%':
        - G
        - I
        - L
        - M
        - N
        - R
        - T
        - U
        - V

# Short descriptions (for proposition/measures) by contest name
short_description:
    Proposition A: City College Job Training, Repair and Earthquake Safety Measure
    Proposition B: San Francisco Earthquake Safety and Emergency Response Bond, 2020
    Proposition C: Retiree Health Care Benefits for Former Employees of the San Francisco Housing Authority
    Proposition D: Vacancy Tax
    Proposition E: Limits on Office Development

contest_name_corrections:
    en:
        - ^{letter}$=Measure {letter}
        - ^{number}$=State Proposition {number}
