# Config for EMS data conversion - name mappings
# Configures district name cleanup, name shortening, classification
#
# The format is a work in progress

#district_classification:
  #- City and County of=County
  #- California State Assembly=Assembly District
  #- Transit=Transit District
  #- Neighborhood=Neighborhood

# Set classification by district code prefix
district_code_classification:
  - 0=County
  - ASSM=Assembly District
  - BART=Transit District
  - MTC=Transit District
  - CITY=City
  - CONG=Congressional District
  - EQUAL=State Tax Board
  - NEIG=Neighborhood
  - SBRA=Park District
  - SFUSD=School District
  - SEN=Senate District
  - SUPV=Supervisorial District
  - APPCT=State Appellate Court District
  - SC=State Superior Court District
  - STATE=State

# Classification codes for results subtotal or precinct grouping
district_grouping:
  - Neighborhood
  - Supervisorial District