# Config for convomniballot.py
# chops the first part of the sequence number used to move RCV to the end
trim_sequence_prefix: 9

contest_map_file: contmap.tsv
candidate_map_file: candmap.tsv

# Number of digits in the bt subdirectory for ballot type number
bt_digits: 2

# The result_style code for turnout giving voting_group_ids and result_stat_type_ids
turnout_result_style: EMTX

# External IDs might not be unique - Add the contest seq prefix
cand_extid_prefix: N

# Patterns to match retention candidate names in retention contest question text
retention_pats:
    - Justice {candidate_name} be elected

approval_required:
    '2/3':
        - D

runoff:
    2018-11-06:
        top_2:
            - GOVERNOR
            - SECRETARY OF STATE
            - CONTROLLER
            - TREASURER
            - ATTORNEY GENERAL
            - INSURANCE COMMISSIONER
            - BOARD OF EQUALIZATION
            - SENATE
            - UNITED STATES
            - ASSEMBLY
            - SUPERINTENDENT OF PUBLIC INSTRUCTION
        non_majority:
            - JUDGE OF THE SUPERIOR COURT

contest_name_corrections:
    en:
        - ^{letter}$=Local Measure {letter}
        - ^{number}$=State Proposition {number}
    es:
        - ^{letter}$=Medida {letter}
        - ^{number}$=Proposición {number}
    tl:
        - ^{letter}$=Sukatin {letter}
        - ^{number}$=Proposisyon {number}
    zh:
        - ^{letter}$=测量{letter}
        - ^{number}$=命题{number}


# The district ID for all voters in this election:
election_voting_district: COSF

# The area ID of the election admin, default is election_voting_district
election_admin_area_id: COSF

district_code_map:
    0: COSF

external_id_prefixes:
    dfm:
        organization: County of San Francisco
        url: https://sfelections.sfgov.org/data-and-maps
        code_group: DFM EMS
    ds:
        organization: County of San Francisco
        url: https://sfelections.sfgov.org/data-and-maps
        code_group: Dominion Democracy Suite
    om:
        organization: Democracy Live
        url: https://sites.omniballot.us/06075/app/sb/election
        code_group: Omniballot RAVBM id
    omx:
        organization: Democracy Live
        url: https://sites.omniballot.us/06075/app/sb/election
        code_group: Omniballot RAVBM external_id
    fp:
        organization: American National Standards Institute
        url: https://www.census.gov/library/reference/code-lists/ansi.html
        code_group: States
    fs:
        organization: American National Standards Institute
        url: https://www.census.gov/library/reference/code-lists/ansi.html
        code_group: Places
        code_prefix: '06'
    fc:
        organization: American National Standards Institute
        url: https://www.census.gov/library/reference/code-lists/ansi.html
        code_group: Counties
        code_prefix: '06'
    fe:
        organization: American National Standards Institute
        url: https://www.census.gov/library/reference/code-lists/ansi.html
        code_group: School Districts
        code_prefix: '06'
    cde:
        organization: California Department of Education
        url: https://www.cde.ca.gov/ds/si/ds/
        code_group: County-District-School Codes
    csc:
        organization: California State Controller
        url: https://bythenumbers.sco.ca.gov/Special-Districts/Special-Districts-Listing/fv6y-3v29
        code_group: Special District Entity ID
    ocd:
        organization: Open Civic Data
        url: https://github.com/opencivicdata/ocd-division-ids
        code_group: OCD-ID
        code_prefix: ocd-division/country:us/state:ca/
    ss:
        organization: California Secretary of State Elections Division
        url: https://www.sos.ca.gov/media/
        code_group: Election night data feed
    sw:
        organization: California Secretary of State Elections Division
        url: https://electionresults.sos.ca.gov/
        code_group: Results web site page ID
        code_url: https://electionresults.sos.ca.gov/returns/{}
