# Config for convomniballot.py
# chops the first part of the sequence number used to move RCV to the end
#trim_sequence_prefix: 9

contest_map_file: contmap.tsv
candidate_map_file: candmap.tsv

# The district ID for all voters in this election:
election_voting_district: 0

# The result_style code for turnout giving voting_group_ids and result_stat_type_ids
turnout_result_style: EMTE

# Number of digits in the bt subdirectory for ballot type number
bt_digits: 3

# Suffix on election-base to select alternate
#election_base_suffix: "-t"

# Patterns to match retention candidate names in retention contest question text
retention_pats:
    - Justice {candidate_name} be elected

# Patterns to match contests restricted to a partisan ballot
contest_party_pats:
    - PRESIDENT OF THE UNITED STATES
    - MEMBER, COUNTY CENTRAL COMMITTEE

contest_party_crossover_pats:
    - PRESIDENT OF THE UNITED STATES{any}DEM
    - PRESIDENT OF THE UNITED STATES{any}LIB
    - PRESIDENT OF THE UNITED STATES{any}AI

url_state_results: https://electionresults.sos.ca.gov/
url_state_results_map:
    - PRESIDENT OF THE UNITED STATES{any}DEM=https://electionresults.sos.ca.gov/returns/president/party/democratic
    - PRESIDENT OF THE UNITED STATES{any}REP=https://electionresults.sos.ca.gov/returns/president/party/republican
    - PRESIDENT OF THE UNITED STATES{any}AI=https://electionresults.sos.ca.gov/returns/president/party/american-independent
    - PRESIDENT OF THE UNITED STATES{any}PF=https://electionresults.sos.ca.gov/returns/president/party/peace-and-freedom
    - PRESIDENT OF THE UNITED STATES{any}LIB=https://electionresults.sos.ca.gov/returns/president/party/libertarian
    - PRESIDENT OF THE UNITED STATES{any}GRN=https://electionresults.sos.ca.gov/returns/president/party/green
    - State Proposition 13=https://electionresults.sos.ca.gov/returns/ballot-measures
    - UNITED STATES REPRESENTATIVE, DISTRICT {number}=https://electionresults.sos.ca.gov/returns/us-rep/district/{number}
    - STATE ASSEMBLY MEMBER, DISTRICT {number}=https://electionresults.sos.ca.gov/returns/state-assembly/district/{number}
    - STATE SENATOR, DISTRICT {number}=https://electionresults.sos.ca.gov/returns/state-senate/district/{number}

approval_required:
    '2/3':
        - B
        - D
    '55%':
        - A

runoff:
    2020-11-03:
        top_2:
            - GOVERNOR
            - SECRETARY OF STATE
            - CONTROLLER
            - TREASURER
            - ATTORNEY GENERAL
            - INSURANCE COMMISSIONER
            - BOARD OF EQUALIZATION
            - SENATE
            - STATE ASSEMBLY MEMBER
            - STATE SENATOR
            - UNITED STATES REPRESENTATIVE
            - SUPERINTENDENT OF PUBLIC INSTRUCTION
        non_majority:
            - JUDGE OF THE SUPERIOR COURT

# Short descriptions (for proposition/measures) by contest name
short_description:
    Proposition 13: School Repair Bond
    Proposition A: City College Job Training, Repair and Earthquake Safety Measure
    Proposition B: San Francisco Earthquake Safety and Emergency Response Bond, 2020
    Proposition C: Retiree Health Care Benefits for Former Employees of the San Francisco Housing Authority
    Proposition D: Vacancy Tax
    Proposition E: Limits on Office Development

contest_name_corrections:
    en:
        - ^{letter}$=Proposition {letter}
        - ^{number}$=State Proposition {number}
